# -*- coding: utf-8 -*-
"""voc_extract_sentiment_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSCBx-VcnPq0LW2_1C1rpdk2wfeMPMon
"""

import glob

transcript_files = glob.glob(
    "sample_transcripts/*.json"
)
print(transcript_files)

print(transcript_files)

print(
    f"Total transcript files found: {len(transcript_files)}"
)

## *******************************************************
## * COPYRIGHT (C) 2025 BCG                          *
##                                                   *
## * This code is the intellectual property of       *
## * BCG. All rights reserved. Unauthorized          *
## * use, modification, or duplication of this code  *
## * without explicit permission from the author     *
## * is strictly prohibited.                         *
## *******************************************************
import asyncio
import json
import logging
from pathlib import Path
from typing import Any
#
import pandas as pd
import glob
import yaml
import torch
#
'''
import click
import pandas as pd
from openpyxl.cell.cell import ILLEGAL_CHARACTERS_RE

from novus_calls.cli.helpers.date_path_resolver import create_resolver_from_config
from novus_calls.cli.utils import log_echo
from novus_calls.core.artifact import ArtifactManager
from novus_calls.core.artifact.utils.path_utils import (
    join_uri,
    normalize_config_paths,
    normalize_dir_uri,
)
from novus_calls.core.callbacks import StdOutCallbackHandler, TrackerCallbackHandler
from novus_calls.core.combiners.voc_table_combiner import VocTableCombiner
from novus_calls.core.extraction.extensions.voc_list_extraction import VocListExtractionExtension
from novus_calls.core.extraction.extensions.voc_structured_extraction import (
    VocStructuredExtractionExtension,
)
from novus_calls.core.extraction.models import (
    ExtractionPipelineRunResultConfig,
    VocListExtractionConfig,
    VocStructuredExtractionConfig,
)
from novus_calls.core.llm import LiteLLMWrapper
from novus_calls.core.llm.main import get_language_models, reset_router
from novus_calls.core.llm.models import RateLimitConfig
from novus_calls.core.tracking import FileStatus, RunTracker, clear_active_tracker, set_active_tracker
from novus_calls.core.tracking.storage import TrackingStorage
from novus_calls.core.utils.async_handler import run_async
from novus_calls.core.utils.log_config import configure_logging
from novus_calls.report.delivery_report_service import send_failure_notification

'''

#

print("Folder created")

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    pipeline,
)
#

logger = logging.getLogger(__name__)

'''
artifact_manager = ArtifactManager()


@click.command(name="voc-extract")
@click.option(
    "--config",
    "-c",
    type=click.Path(exists=True),
    required=True,
    help="Path to VOC pipeline configuration YAML file",
)
@click.option(
    "--max-files",
    type=int,
    default=None,
    help="Maximum number of transcript files to process (for testing)",
)
@click.option(
    "--databricks/--no-databricks",
    default=False,
    help="Enable or disable Databricks upsert (default: disabled)",
)
@click.option(
    "--target-date",
    default=None,
    help="Target date in YYYY-MM-DD format (defaults to yesterday)",
)
@click.option("--date-path", "use_date_paths", flag_value=True, default=None)
@click.option("--no-date-path", "use_date_paths", flag_value=False)
@click.option(
    "--verbose",
    "-v",
    is_flag=True,
    default=False,
    help="Enable verbose callback output for debugging",
)
def voc_extract(
    config: str,
    max_files: int | None,
    databricks: bool,
    target_date: str | None,
    use_date_paths: bool | None,
    verbose: bool,
) -> None:
    """Run the Voice of Customer extraction pipeline.

    Processes transcripts through a two-stage extraction process (initial
    screening followed by conditional detailed extraction), aggregates
    results into a combined Excel table, and optionally upserts to a
    Databricks Delta table.

    Args:
        config: Path to the VOC pipeline configuration YAML file.
        max_files: Maximum number of transcript files to process. ``None``
            processes all available files.
        databricks: When ``True``, upsert combined results to Databricks.
        target_date: Target date (YYYY-MM-DD) for date-based path
            resolution. Defaults to yesterday when ``None``.
        use_date_paths: When ``True``, enables date-based path resolution.
            When ``None``, falls back to the config's ``USE_DATE_PATHS``.
        verbose: When ``True``, attaches a ``StdOutCallbackHandler`` for
            detailed progress output.

    Raises:
        click.ClickException: If the pipeline execution fails.
    """
    log_echo(click.style("\nVOC Extraction Pipeline", fg="cyan", bold=True))
    log_echo(f"Configuration: {config}")
    log_echo(f"Max files: {max_files if max_files else 'All'}")
    log_echo(f"Databricks: {'Enabled' if databricks else 'Disabled'}\n")

    # Run the async workflow
    try:
        run_async(run_voc_pipeline(config, max_files, databricks, target_date, use_date_paths, verbose))
        log_echo(click.style("\nVOC Pipeline Completed Successfully!", fg="green", bold=True))
    except Exception as e:
        logger.exception("VOC pipeline execution failed")
        log_echo(click.style(f"\nPipeline Failed: {e}", fg="red", bold=True))
        # Send failure notification if configured
        try:
            config_data = artifact_manager.read_yaml(config)
            failure_config = config_data.get("FAILURE_NOTIFICATION", {})
            if failure_config.get("enabled"):
                send_failure_notification(
                    command="voc-extract",
                    error=e,
                    config_path=config,
                    recipients=failure_config.get("recipients", []),
                    sender_email=failure_config.get("sender_email", ""),
                    artifact_manager=artifact_manager,
                )
        except Exception as notify_err:
            logger.warning(f"Failed to send failure notification: {notify_err}")
        raise click.ClickException(str(e)) from e


async def run_voc_pipeline(
    config_path: str,
    max_files: int | None,
    enable_databricks: bool,
    target_date: str | None,
    use_date_paths: bool | None,
    verbose: bool = False,
) -> None:
    """Execute the full async VOC extraction workflow.

    Orchestrates the five pipeline stages: load transcripts, initial
    screening, conditional detailed extraction, table combination, and
    optional Databricks upsert. Manages run tracking, callbacks, and
    failure notifications throughout.

    Args:
        config_path: Path to the VOC pipeline YAML configuration file.
        max_files: Cap on the number of transcript files to process.
            ``None`` means process all available files.
        enable_databricks: When ``True``, upsert the combined table to a
            Databricks Delta table after combination.
        target_date: Target date (YYYY-MM-DD) for date-based path
            resolution. Defaults to yesterday when ``None``.
        use_date_paths: Override for date-based path resolution. ``None``
            falls back to the config's ``USE_DATE_PATHS``.
        verbose: When ``True``, attaches a ``StdOutCallbackHandler``.
    """
    # Initialize ArtifactManager first
    artifact_manager = ArtifactManager()

    # Set up callbacks
    callbacks = []
    if verbose:
        callbacks.append(StdOutCallbackHandler())

    # Load configuration using ArtifactManager
    config = normalize_config_paths(artifact_manager.read_yaml(config_path))
    # Setup VOC paths with date resolution using helper
    config, transcript_path, raw_features_path, combined_table_path, transformation_config, path_resolver = (
        _setup_voc_paths(config, target_date, use_date_paths)
    )

    # Initialize run tracker
    tracking_path = config.get("TRACKING_PATH")
    tracking_storage = None
    if tracking_path:
        tracking_storage = TrackingStorage(
            artifact_manager=artifact_manager,
            base_path=tracking_path,
        )
    tracker = RunTracker(
        command="voc-extract",
        config_path=config_path,
        storage=tracking_storage,
        target_date=path_resolver.date_str,
    )
    tracker.start()
    set_active_tracker(tracker)

    # Add tracker callback handler now that tracker is initialized
    tracker_handler = TrackerCallbackHandler(tracker)
    callbacks.append(tracker_handler)

    # Resolve all config paths using helper
    config = _resolve_all_config_paths(config)

    # Get rate limits from config for parallel processing
    rate_limits_config = config.get("RATE_LIMITS")
    rate_limits = None
    if rate_limits_config:
        rate_limits = RateLimitConfig(
            rpm=rate_limits_config.get("rpm", 60),
            tpm=rate_limits_config.get("tpm", 90000),
            azure_rpm=rate_limits_config.get("azure_rpm"),
            azure_tpm=rate_limits_config.get("azure_tpm"),
        )
        log_echo(f"Rate limits enabled: rpm={rate_limits.rpm}, tpm={rate_limits.tpm}")
    else:
        # Use default rate limits for VOC parallel processing
        rate_limits = RateLimitConfig()
        log_echo(f"Using default rate limits: rpm={rate_limits.rpm}, tpm={rate_limits.tpm}")

    # Reset router to ensure fresh configuration
    reset_router()

    # Store rate_limits in config for sub-functions to use
    config["_rate_limits"] = rate_limits

    # STEP 1: Load transcripts
    log_echo(click.style("\nStep 1: Loading Transcripts", fg="yellow", bold=True))

    # List transcript files
    transcript_uris = artifact_manager.list_objects(transcript_path, extensions=[".json"])
    if max_files:
        transcript_uris = transcript_uris[:max_files]

    log_echo(f"Found {len(transcript_uris)} transcript files to process")

    # STEP 2: Run initial screening
    log_echo(click.style("\nStep 2: Running Initial Screening", fg="yellow", bold=True))
    screening_results, screening_errors = await run_initial_screening(
        transcript_uris, config, raw_features_path, artifact_manager
    )
    log_echo(f"Completed screening for {len(screening_results)} transcripts")

    # Track file processing results
    for result in screening_results:
        tracker.track_file(
            result.get("filename", "unknown"),
            FileStatus.SUCCESS,
            file_type="transcript",
        )
    for error_info in screening_errors:
        tracker.track_file(
            error_info.get("filename", "unknown"),
            FileStatus.FAILED,
            file_type="transcript",
            error_type=error_info.get("error_type", "ProcessingError"),
            error_message=error_info.get("error_message"),
        )

    # STEP 3: Run conditional detailed extraction
    log_echo(click.style("\nStep 3: Running Detailed Extraction", fg="yellow", bold=True))

    # Debug: Show sample screening result to understand structure
    if screening_results:
        sample = screening_results[0]
        log_echo("\nDebug - Sample screening result:")
        for key, value in sample.items():
            if key != "filename":
                log_echo(f"  {key}: {value} (type: {type(value).__name__})")

    detailed_results = await run_detailed_extraction(screening_results, config, raw_features_path)
    log_echo(f"Completed detailed extraction for {sum(len(v) for v in detailed_results.values())} items")

    # STEP 4: Combine and aggregate
    log_echo(click.style("\nStep 4: Combining and Aggregating Results", fg="yellow", bold=True))
    combined_df = combine_voc_results(screening_results, detailed_results, transformation_config, artifact_manager)
    safe_combined_df = _ensure_excel_safe_dataframe(combined_df)

    # Save combined results using ArtifactManager
    artifact_manager.write_df_as_excel({"combined": safe_combined_df}, combined_table_path)
    log_echo(f"Saved combined table: {combined_table_path}")
    log_echo(f"Total rows: {len(combined_df)}, Total columns: {len(combined_df.columns)}")

    # STEP 5: Upload to Databricks (optional)
    if enable_databricks:
        log_echo(click.style("\nStep 5: Uploading to Databricks", fg="yellow", bold=True))
        await upload_to_databricks(combined_df, config)
        log_echo("Databricks upload completed")
    else:
        log_echo("\nSkipping Databricks upload (--no-databricks)")

    # Complete run tracking
    tracker.complete()
    clear_active_tracker()
    summary = tracker.get_summary()
    log_echo(
        f"\nRun tracking: {summary['total_files']} files processed, "
        f"{summary['success_count']} success, {summary['failed_count']} failed, "
        f"{summary['skipped_count']} skipped"
    )

    # Send failure notification if there were any partial failures (even if not a full exception)
    if summary.get("failed_count", 0) > 0 or screening_errors:
        failure_config = config.get("FAILURE_NOTIFICATION", {})
        if failure_config.get("enabled"):
            failed_count = summary.get("failed_count", 0)
            error_msg = f"Failed to process {failed_count} files during VOC extraction"
            if screening_errors:
                sample_errors = [e.get("error_message", "Unknown") for e in screening_errors[:3]]
                error_msg += f". Sample errors: {'; '.join(sample_errors)}"
            try:
                send_failure_notification(
                    command="voc-extract",
                    error=Exception(error_msg),
                    config_path=config_path,
                    recipients=failure_config.get("recipients", []),
                    sender_email=failure_config.get("sender_email", ""),
                    artifact_manager=artifact_manager,
                    run_summary=summary,
                )
                log_echo(click.style("Partial failure notification sent", fg="yellow"))
            except Exception as notify_err:
                logger.warning(f"Failed to send partial failure notification: {notify_err}")


def _sanitize_excel_value(value: Any) -> Any:
    """Remove characters that Excel cannot handle and normalize complex objects.

    Args:
        value: Any cell value. Strings are stripped of illegal XML
            characters, bytes are decoded to UTF-8, and dicts/lists are
            JSON-encoded before sanitization.

    Returns:
        The sanitized value, or the original value unchanged for numeric
        and ``None`` types.
    """
    if value is None:
        return value

    try:
        if pd.isna(value):
            return value
    except TypeError:
        logger.debug("Non-scalar value encountered during Excel sanitization")
        # Non-numeric/non-scalar types can raise when checked with pd.isna

    if isinstance(value, str):
        return ILLEGAL_CHARACTERS_RE.sub("", value)

    if isinstance(value, bytes):
        decoded = value.decode("utf-8", errors="ignore")
        return ILLEGAL_CHARACTERS_RE.sub("", decoded)

    if isinstance(value, (dict, list)):
        try:
            encoded = json.dumps(value, ensure_ascii=False)
        except (TypeError, ValueError):
            logger.debug("Failed to JSON-encode value for Excel sanitization")
            encoded = str(value)
        return ILLEGAL_CHARACTERS_RE.sub("", encoded)

    return value


def _ensure_excel_safe_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """Sanitize object-type columns so Excel saves without encoding errors.

    Args:
        df: DataFrame to sanitize. Only ``object`` and ``string`` dtype
            columns are processed.

    Returns:
        A copy of the DataFrame with illegal XML characters removed from
        string-like columns. Returns the original DataFrame unchanged when
        it is empty.
    """
    if df.empty:
        return df

    safe_df = df.copy()
    object_columns = safe_df.select_dtypes(include=["object", "string"])

    if not object_columns.empty:
        safe_df[object_columns.columns] = object_columns.map(_sanitize_excel_value)

    return safe_df


def _resolve_config_path(path: str, base_config_folder: str | None) -> str:
    """Resolve a config path relative to ``base_config_folder``.

    Absolute paths and URIs (``s3://``, ``azblob://``, etc.) are returned
    unchanged. Relative paths are joined with ``base_config_folder``.

    Args:
        path: The path to resolve (absolute, relative, or URI).
        base_config_folder: Base directory to prepend to relative paths.
            When ``None`` or empty, the original path is returned as-is.

    Returns:
        Resolved absolute path, or the original path when no resolution
        is needed.
    """
    if not base_config_folder or not path:
        return path

    # Don't modify absolute paths or URIs (s3://, azblob://, etc.)
    if path.startswith("/") or "://" in path:
        return path

    # Join base_config_folder with relative path
    from pathlib import Path

    resolved = str(Path(base_config_folder) / path)
    logger.debug(f"Resolved config path: {path} -> {resolved}")
    return resolved


def _resolve_all_config_paths(config: dict) -> dict:
    """Resolve all relative paths in config based on ``base_config_folder``.

    Resolves paths in global parameters, pipeline step configs
    (``fields_config``, ``templates_path``), and transformation configs
    (``field_mappings``, ``aggregation_rules``, ``final_columns``).

    Args:
        config: VOC pipeline config dict. Must contain
            ``base_config_folder`` for resolution to take effect.

    Returns:
        The same config dict with relative paths replaced by absolute ones.
        Returned unchanged when ``base_config_folder`` is not set.
    """
    base_config_folder = config.get("base_config_folder")
    if not base_config_folder:
        return config

    logger.info(f"Using base config folder: {base_config_folder}")

    # Resolve paths in global parameters
    for key, value in config.get("parameters", {}).items():
        if isinstance(value, str):
            config["parameters"][key] = _resolve_config_path(value, base_config_folder)

    # Resolve paths in pipeline steps
    for step in config.get("steps", []):
        for path_key in ["fields_config", "templates_path"]:
            if path_key in step:
                step[path_key] = _resolve_config_path(step[path_key], base_config_folder)

    # Resolve paths in transformation config
    transformation = config.get("transformation", {})
    for key in ["field_mappings", "aggregation_rules", "final_columns"]:
        if key in transformation:
            transformation[key] = _resolve_config_path(transformation[key], base_config_folder)

    return config


def _setup_voc_paths(config: dict, target_date: str | None, use_date_paths: bool | None):
    """Set up input/output paths with optional date-based resolution.

    Creates a ``DatePathResolver`` and resolves transcript, raw feature,
    and combined table paths from the config's ``input`` and ``output``
    sections.

    Args:
        config: VOC pipeline config dict containing ``input``, ``output``,
            ``transformation``, and optionally ``USE_DATE_PATHS``.
        target_date: Target date (YYYY-MM-DD) for the path resolver.
            Defaults to yesterday when ``None``.
        use_date_paths: Explicit override for date-based resolution.
            ``None`` defers to config's ``USE_DATE_PATHS``.

    Returns:
        Tuple of ``(config, transcript_path, raw_features_path,
        combined_table_path, transformation_config, path_resolver)``.
    """
    input_config = config.get("input", {})
    output_config = config.get("output", {})
    transformation_config = config.get("transformation", {})

    if use_date_paths is None:
        use_date_paths = bool(config.get("USE_DATE_PATHS", False))

    # Use date-based path resolution when enabled
    path_resolver = create_resolver_from_config(config, target_date=target_date)
    if use_date_paths:
        log_echo(f"Using date-based path resolution (target_date: {target_date or 'yesterday'})")
        log_echo(f"Path resolver: {path_resolver}")

    # Update config with resolved paths
    config = path_resolver.resolve_config_paths(config, config_type="voc", enabled=use_date_paths)
    input_config = config.get("input", {})
    output_config = config.get("output", {})

    log_echo(f"Resolved transcript path: {input_config.get('transcript_path')}")
    log_echo(f"Resolved raw features path: {output_config.get('raw_features_path')}")
    log_echo(f"Resolved combined table path: {output_config.get('combined_table_path')}")

    transcript_path = normalize_dir_uri(input_config.get("transcript_path", "client_data/novus/transcripts/calls/"))
    raw_features_path = normalize_dir_uri(
        output_config.get("raw_features_path", "client_data/novus/output/voc_features/raw/")
    )
    combined_table_path = output_config.get(
        "combined_table_path", "client_data/novus/output/voc_features/combined/voc_combined.xlsx"
    )

    logger.info(f"Transcript path: {transcript_path}")
    logger.info(f"Raw features path: {raw_features_path}")
    logger.info(f"Combined table path: {combined_table_path}")

    return config, transcript_path, raw_features_path, combined_table_path, transformation_config, path_resolver


def _resolve_parameters(step_parameters: dict, global_parameters: dict) -> dict:
    """Resolve ``${parameters.*}`` substitutions in step parameters.

    Replaces references like ``${parameters.insurance_providers}`` with the
    corresponding value from the global parameters dict.

    Args:
        step_parameters: Step-level parameter dict that may contain
            ``${parameters.*}`` placeholder strings.
        global_parameters: Top-level ``parameters`` dict from the pipeline
            config, used to resolve references.

    Returns:
        New dict with all ``${parameters.*}`` references replaced by their
        resolved values. Non-reference values are passed through unchanged.
    """
    resolved = {}
    for key, value in step_parameters.items():
        if isinstance(value, str) and value.startswith("${parameters.") and value.endswith("}"):
            # Extract parameter name: ${parameters.insurance_providers} -> insurance_providers
            param_name = value[len("${parameters.") : -1]
            if param_name in global_parameters:
                resolved[key] = global_parameters[param_name]
            else:
                logger.warning(f"Parameter {param_name} not found in global parameters, using as-is")
                resolved[key] = value
        else:
            resolved[key] = value
    return resolved


async def run_initial_screening(
    transcript_uris: list[str], config: dict, output_path: str, artifact_manager: ArtifactManager
) -> tuple[list[dict], list[dict]]:
    """Run initial screening on all transcripts in parallel.

    Creates a ``VocStructuredExtractionExtension`` from the
    ``initial_screening`` step config and processes every transcript
    concurrently via ``asyncio.gather``. Results are saved as individual
    JSON files under ``{output_path}/screening/``.

    Args:
        transcript_uris: List of URIs/paths to transcript JSON files.
        config: VOC pipeline config dict containing ``steps`` (must include
            an ``initial_screening`` entry), ``DEFAULT_LANGUAGE_MODEL``,
            ``parameters``, and ``_rate_limits``.
        output_path: Base output directory for raw features. Screening
            results are written to the ``screening/`` subdirectory.
        artifact_manager: ``ArtifactManager`` instance for file I/O.

    Returns:
        Tuple of ``(successful_results, error_results)``.
        Each successful result is a dict with ``filename`` and extracted
        fields. Each error result contains ``filename``, ``error_type``,
        and ``error_message``.

    Raises:
        ValueError: If no ``initial_screening`` step is found in config.
    """
    log_echo(f"Processing {len(transcript_uris)} transcripts...")

    # Get steps from config (not nested under 'pipeline')
    steps = config.get("steps", [])

    # Find initial_screening step
    screening_step_config = None
    for step in steps:
        if step.get("name") == "initial_screening":
            screening_step_config = step
            break

    if not screening_step_config:
        raise ValueError(
            "Initial screening step not found in config. Available steps: "
            + ", ".join([s.get("name", "unnamed") for s in steps])
        )

    # Resolve parameter substitutions
    parameters = screening_step_config.get("parameters", {})
    resolved_parameters = _resolve_parameters(parameters, config.get("parameters", {}))

    # Get default language model from config
    default_language_model = config.get("DEFAULT_LANGUAGE_MODEL", "gpt-5-mini")

    # Create extension
    step_obj = VocStructuredExtractionConfig(
        name=screening_step_config["name"],
        type=screening_step_config["type"],
        language_model=screening_step_config.get("language_model", default_language_model),
        fields_config=screening_step_config["fields_config"],
        parameters=resolved_parameters,
    )

    extension = VocStructuredExtractionExtension(pipeline_step=step_obj)

    # Get language models with rate limiting
    model_name = screening_step_config.get("language_model", default_language_model)
    rate_limits = config.get("_rate_limits")
    models_dict = get_language_models(models={model_name}, rate_limits=rate_limits)
    llm = models_dict[model_name]

    # Process transcripts in parallel
    tasks = [
        _process_single_transcript(transcript_uri, extension, llm, artifact_manager)
        for transcript_uri in transcript_uris
    ]

    # Run all tasks
    results = await asyncio.gather(*tasks, return_exceptions=True)

    # Filter successful results and collect errors
    screening_results = []
    screening_errors = []
    for i, result in enumerate(results):
        if isinstance(result, Exception):
            # Extract filename from URI for error message
            uri_filename = transcript_uris[i].split("/")[-1]
            log_echo(f"Error processing {uri_filename}: {result}")
            screening_errors.append(
                {
                    "filename": uri_filename,
                    "error_type": type(result).__name__,
                    "error_message": str(result),
                }
            )
        else:
            screening_results.append(result)

    log_echo(f"Successfully processed {len(screening_results)}/{len(transcript_uris)} transcripts")

    # Save raw screening results
    if output_path and screening_results:
        # Save individual screening results as JSON files
        screening_output_path = join_uri(output_path, "screening")

        for result in screening_results:
            filename = result.get("filename", "unknown")
            base_name = Path(filename).stem
            output_file = join_uri(screening_output_path, f"{base_name}_screening.json")
            artifact_manager.write_json(output_file, result)

        log_echo(f"Saved {len(screening_results)} screening results to {screening_output_path}")

    return screening_results, screening_errors


async def _process_single_transcript(
    transcript_uri: str,
    extension: VocStructuredExtractionExtension,
    llm: LiteLLMWrapper,
    artifact_manager: ArtifactManager,
) -> dict:
    """Process a single transcript through the screening extension.

    Loads the transcript JSON, extracts the text (handling nested Azure
    Speech format), runs the screening extension, and parses the LLM
    result into a flat dict.

    Args:
        transcript_uri: Full URI or path to the transcript JSON file.
        extension: Initialized ``VocStructuredExtractionExtension`` for
            the screening step.
        llm: LLM wrapper instance for the screening model.
        artifact_manager: ``ArtifactManager`` instance for reading the
            transcript file.

    Returns:
        Dict containing ``filename``, transcript metadata, and all
        extracted screening fields.
    """
    # Extract filename from URI
    filename = transcript_uri.split("/")[-1]

    # Load transcript using ArtifactManager
    transcript_data = artifact_manager.read_json(transcript_uri)

    # Extract transcript text - handle nested structure
    if isinstance(transcript_data, dict):
        # Try nested transcription.transcript first (Azure Speech format)
        if "transcription" in transcript_data and isinstance(transcript_data["transcription"], dict):
            transcript_text = transcript_data["transcription"].get("transcript", "")
        # Fall back to direct keys
        else:
            transcript_text = transcript_data.get("transcript", transcript_data.get("text", str(transcript_data)))
    else:
        transcript_text = str(transcript_data)

    # Extract metadata from transcript_data
    metadata = transcript_data.get("metadata", {}) if isinstance(transcript_data, dict) else {}

    # Create context
    context = ExtractionPipelineRunResultConfig(
        text=transcript_text,
        metadata={"filename": filename, **metadata},
        responses=[],
    )

    # Run extraction
    result = await extension.run(context=context, llm=llm)

    # Parse the result - handle both dict and JSON string
    logger.debug(f"Screening result.answer type: {type(result.answer)}")
    logger.debug(f"Screening result.answer: {result.answer}")

    if isinstance(result.answer, dict):
        result_dict = result.answer
    elif isinstance(result.answer, str):
        try:
            # Try to parse as JSON
            result_dict = json.loads(result.answer)
            logger.debug(f"Parsed JSON result_dict: {result_dict}")
        except json.JSONDecodeError:
            logger.warning("Failed to parse screening result as JSON: %s", result.answer)
            result_dict = {"result": result.answer}
    else:
        result_dict = {"result": result.answer}

    # Keep "response_" prefix for screening results (needed for field mappings)
    # The VocTableCombiner expects these field names
    logger.debug(f"Result dict keys: {list(result_dict.keys())}")

    # Combine filename, metadata, and extraction results
    output = {"filename": filename, **metadata, **result_dict}

    return output


def _build_transcript_uri_map(config: dict) -> dict[str, str]:
    """Build a filename-to-URI mapping for all transcripts in the input path.

    Args:
        config: VOC pipeline config dict with ``input.transcript_path``.

    Returns:
        Dict mapping each transcript's basename (e.g. ``"call_001.json"``)
        to its full URI.
    """
    artifact_manager = ArtifactManager()
    input_path = config.get("input", {}).get("transcript_path", "")

    log_echo(f"Building transcript URI index from {input_path}...")
    all_transcript_uris = artifact_manager.list_objects(input_path, extensions=[".json"])

    transcript_uri_map = {uri.split("/")[-1]: uri for uri in all_transcript_uris}
    log_echo(f"Indexed {len(transcript_uri_map)} transcript URIs")
    return transcript_uri_map


def _check_condition_match(screening_result: dict, if_condition: dict) -> bool:
    """Check if a screening result field matches an expected value.

    Performs case-insensitive comparison. Handles fields with or without
    the ``response_`` prefix that the screening step may add.

    Args:
        screening_result: Dict from initial screening containing extracted
            field values keyed by field name (optionally prefixed).
        if_condition: Dict with ``field`` (field name to check) and
            ``has_value`` (expected value to match).

    Returns:
        ``True`` when the field's actual value matches the expected value
        (case-insensitive, stripped); ``False`` otherwise.
    """
    field = if_condition.get("field")
    expected_value = if_condition.get("has_value")

    # Field names in screening results have "response_" prefix
    field_with_prefix = f"response_{field}" if not field.startswith("response_") else field
    actual_value = screening_result.get(field_with_prefix, screening_result.get(field))

    # Normalize values for comparison
    actual_normalized = str(actual_value).lower().strip() if actual_value else ""
    expected_normalized = str(expected_value).lower().strip() if expected_value else ""

    return actual_normalized == expected_normalized


def _process_extraction_results(results: list, task_metadata: list[dict]) -> dict[str, list[dict]]:
    """Organize detailed extraction results by category (step name).

    Pairs each ``asyncio.gather`` result with its task metadata to group
    items by extraction step name. Exceptions and ``None`` results are
    skipped.

    Args:
        results: Raw results from ``asyncio.gather``, which may include
            dicts, lists of dicts, ``Exception`` instances, or ``None``.
        task_metadata: List of metadata dicts (same order as ``results``)
            with ``step_name`` and ``filename`` keys.

    Returns:
        Dict mapping category names (step names) to lists of result dicts,
        each annotated with a ``filename`` key.
    """
    detailed_by_category = {}

    for i, result in enumerate(results):
        if isinstance(result, Exception):
            logger.error(f"Error in detailed extraction {task_metadata[i]}: {result}")
            continue

        if result is None:
            continue

        step_name = task_metadata[i]["step_name"]
        filename = task_metadata[i]["filename"]

        category = step_name
        if category not in detailed_by_category:
            detailed_by_category[category] = []

        if isinstance(result, list):
            for item in result:
                item["filename"] = filename
                detailed_by_category[category].append(item)
        elif isinstance(result, dict):
            result["filename"] = filename
            detailed_by_category[category].append(result)

    return detailed_by_category


def _save_detailed_results(detailed_by_category: dict[str, list[dict]], output_path: str) -> None:
    """Save detailed extraction results as JSON files organized by category.

    Each item is written to
    ``{output_path}/{category}/{basename}_{category}_{index}.json``.

    Args:
        detailed_by_category: Dict mapping category names to lists of
            result dicts. Each dict must contain a ``filename`` key.
        output_path: Base output directory. No-op when empty or ``None``.
    """
    if not output_path or not detailed_by_category:
        return

    artifact_manager = ArtifactManager()
    total_items = sum(len(items) for items in detailed_by_category.values())

    for category, items in detailed_by_category.items():
        category_output_path = join_uri(output_path, category)

        for idx, item in enumerate(items):
            filename = item.get("filename", "unknown")
            base_name = Path(filename).stem
            output_file = join_uri(category_output_path, f"{base_name}_{category}_{idx}.json")
            artifact_manager.write_json(output_file, item)

    log_echo(f"Saved {total_items} detailed results to {output_path}")


def _collect_extraction_tasks(
    screening_results: list[dict],
    initial_step: dict,
    step_map: dict[str, dict],
    transcript_uri_map: dict[str, str],
    config: dict,
) -> tuple:
    """Collect detailed extraction coroutines based on screening conditions.

    Iterates over screening results and the initial step's ``next_steps``
    routing rules. For each condition that matches, creates a
    ``_run_detailed_step`` coroutine for every target step.

    Args:
        screening_results: List of screening result dicts from
            ``run_initial_screening``.
        initial_step: The ``initial_screening`` step config dict containing
            ``next_steps`` routing rules.
        step_map: Dict mapping step names to their config dicts.
        transcript_uri_map: Filename-to-URI mapping from
            ``_build_transcript_uri_map``.
        config: Global VOC pipeline config passed to each extraction task.

    Returns:
        Tuple of ``(tasks, task_metadata)`` where ``tasks`` is a list of
        coroutines and ``task_metadata`` is a parallel list of dicts with
        ``filename``, ``transcript_uri``, ``step_name``, and ``step_type``.
    """
    tasks = []
    task_metadata = []
    conditions_checked = 0
    conditions_matched = 0

    for screening_result in screening_results:
        filename = screening_result.get("filename")
        transcript_uri = transcript_uri_map.get(filename)

        if not transcript_uri:
            logger.warning(f"Could not find transcript URI for {filename}")
            continue

        for next_step_rule in initial_step.get("next_steps", []):
            if_condition = next_step_rule.get("if_llm_answer", {})
            target_steps = if_condition.get("go_to", [])
            conditions_checked += 1

            if _check_condition_match(screening_result, if_condition):
                conditions_matched += 1
                for target_step_name in target_steps:
                    if target_step_name in step_map:
                        step_config = step_map[target_step_name]
                        tasks.append(_run_detailed_step(transcript_uri, step_config, config))
                        task_metadata.append(
                            {
                                "filename": filename,
                                "transcript_uri": transcript_uri,
                                "step_name": target_step_name,
                                "step_type": step_config.get("type"),
                            }
                        )

    log_echo(f"Checked {conditions_checked} conditions, matched {conditions_matched}")
    return tasks, task_metadata
'''

#
def _extract_transcript_text(transcript_data) -> str:
    """Extract transcript text from various JSON data formats.

    Handles Azure Speech nested format (``transcription.transcript``),
    flat ``conversation``/``text`` keys, and non-dict inputs.

    Args:
        transcript_data: Parsed transcript JSON (dict or other).

    Returns:
        Extracted text string. Falls back to ``str()`` conversion for
        non-dict inputs.
    """
    if isinstance(transcript_data, dict):
        # Try nested transcription.transcript first (Azure Speech format)
        if "transcription" in transcript_data and isinstance(transcript_data["transcription"], dict):
            return transcript_data["transcription"].get("transcript", "")
        # Fall back to direct keys
        return transcript_data.get("conversation", transcript_data.get("text", ""))
    return str(transcript_data)

def extract_customer_only_text(
transcript_text
):

    customer_lines = []

    for line in transcript_text.split("\n"):

        line = line.strip()

        if line.startswith("Customer:"):

            cleaned = line.replace(
                "Customer:",
                ""
            ).strip()

            customer_lines.append(cleaned)

    return " ".join(customer_lines)
#
'''

def _parse_structured_result(answer) -> dict:
    """Parse a structured extraction answer into a plain dict.

    Args:
        answer: The LLM answer, which may be a dict, a JSON string, or
            another type.

    Returns:
        Parsed dict. JSON strings are deserialized; other types are
        wrapped as ``{"result": answer}``.
    """
    if isinstance(answer, dict):
        return answer
    if isinstance(answer, str):
        try:
            return json.loads(answer)
        except json.JSONDecodeError:
            logger.warning("Failed to parse detailed extraction result as JSON: %s", answer)
            return {"result": answer}
    return {"result": answer}


async def run_detailed_extraction(
    screening_results: list[dict], config: dict, output_path: str
) -> dict[str, list[dict]]:
    """Run conditional detailed extraction based on screening flags.

    Evaluates the ``initial_screening`` step's ``next_steps`` routing
    rules against each screening result, dispatches matching transcripts
    to the appropriate ``voc_structured_extraction`` or
    ``voc_list_extraction`` step, and saves results by category.

    Args:
        screening_results: List of screening result dicts from
            ``run_initial_screening``.
        config: VOC pipeline config dict containing ``steps``,
            ``parameters``, ``input.transcript_path``, and ``_rate_limits``.
        output_path: Base directory for saving per-category extraction
            JSON files.

    Returns:
        Dict mapping category names (step names) to lists of result dicts.
        Returns an empty dict when no ``initial_screening`` step is found.
    """
    steps = config.get("steps", [])
    initial_step = next((s for s in steps if s.get("name") == "initial_screening"), None)

    if not initial_step:
        return {}

    # Build map of step names to configs
    step_map = {step["name"]: step for step in steps}

    # Pre-load transcript URI mapping using helper
    transcript_uri_map = _build_transcript_uri_map(config)

    # Collect all extraction tasks
    tasks, task_metadata = _collect_extraction_tasks(
        screening_results, initial_step, step_map, transcript_uri_map, config
    )

    log_echo(f"Running {len(tasks)} detailed extraction tasks...")

    # Execute all tasks in parallel
    results = await asyncio.gather(*tasks, return_exceptions=True)

    # Process and organize results using helper
    detailed_by_category = _process_extraction_results(results, task_metadata)

    # Log summary
    total_items = sum(len(items) for items in detailed_by_category.values())
    log_echo(f"Extracted {total_items} detailed items across {len(detailed_by_category)} categories")

    # Save raw detailed results using helper
    _save_detailed_results(detailed_by_category, output_path)

    return detailed_by_category


async def _run_detailed_step(transcript_uri: str, step_config: dict, global_config: dict) -> list[dict] | dict | None:
    """Run a single detailed extraction step on one transcript.

    Instantiates the appropriate extension
    (``VocStructuredExtractionExtension`` or ``VocListExtractionExtension``)
    from the step config, acquires a rate-limited LLM, and runs extraction.

    Args:
        transcript_uri: Full URI/path to the transcript JSON file.
        step_config: Step-level config dict with ``name``, ``type``,
            ``fields_config``, ``language_model``, and ``parameters``.
        global_config: Global VOC pipeline config providing
            ``DEFAULT_LANGUAGE_MODEL``, ``parameters``, and ``_rate_limits``.

    Returns:
        A dict (for structured extraction), a list of dicts (for list
        extraction), or ``None`` when extraction fails or finds no
        relevant information.

    Raises:
        ValueError: If ``step_config["type"]`` is not a recognized
            extraction type.
    """
    step_type = step_config.get("type")
    step_name = step_config.get("name")

    # Load transcript using the full URI
    artifact_manager = ArtifactManager()
    transcript_data = artifact_manager.read_json(transcript_uri)

    # Extract filename from URI for metadata
    filename = transcript_uri.split("/")[-1]

    # Extract text using helper
    transcript_text = _extract_transcript_text(transcript_data)

    # Resolve parameters
    parameters = step_config.get("parameters", {})
    resolved_parameters = _resolve_parameters(parameters, global_config.get("parameters", {}))

    # Get language model with rate limiting
    default_language_model = global_config.get("DEFAULT_LANGUAGE_MODEL", "gpt-5-mini")
    model_name = step_config.get("language_model", default_language_model)
    rate_limits = global_config.get("_rate_limits")
    models_dict = get_language_models(models={model_name}, rate_limits=rate_limits)
    llm = models_dict[model_name]

    # Create context
    context = ExtractionPipelineRunResultConfig(
        text=transcript_text,
        metadata={"filename": filename},
        responses=[],
    )

    # Validate step_type before try block
    if step_type not in ("voc_structured_extraction", "voc_list_extraction"):
        raise ValueError(f"Unknown step type: {step_type}")

    try:
        if step_type == "voc_structured_extraction":
            step_obj = VocStructuredExtractionConfig(
                name=step_name,
                type=step_type,
                language_model=model_name,
                fields_config=step_config["fields_config"],
                parameters=resolved_parameters,
            )
            extension = VocStructuredExtractionExtension(pipeline_step=step_obj)
            result = await extension.run(context=context, llm=llm)
            return _parse_structured_result(result.answer)

        if step_type == "voc_list_extraction":
            step_obj = VocListExtractionConfig(
                name=step_name,
                type=step_type,
                language_model=model_name,
                fields_config=step_config["fields_config"],
                parameters=resolved_parameters,
                max_items=step_config.get("max_items", 10),
            )
            extension = VocListExtractionExtension(pipeline_step=step_obj)
            result = await extension.run(context=context, llm=llm)
            return result.answer if isinstance(result.answer, list) else [result.answer]

    except Exception as e:
        logger.exception("Detailed extraction failed for %s in %s", step_name, filename)
        # Log validation errors or extraction failures
        # Return None to indicate no information was found
        error_msg = str(e)
        if "validation error" in error_msg.lower():
            logger.info(f"No relevant information found for {step_name} in {filename}")
        else:
            logger.warning(f"Error in detailed extraction for {step_name} in {filename}: {e}")
        return None


def combine_voc_results(
    screening_results: list[dict],
    detailed_results: dict[str, list[dict]],
    transformation_config: dict,
    artifact_manager: ArtifactManager,
) -> pd.DataFrame:
    """Combine screening and detailed results into a final aggregated table.

    Converts results to DataFrames and delegates to ``VocTableCombiner``
    which applies field mappings, derived columns, aggregation rules, and
    final column ordering.

    Args:
        screening_results: List of screening result dicts (one per
            transcript).
        detailed_results: Dict mapping category names to lists of detailed
            extraction result dicts.
        transformation_config: Dict containing paths to ``field_mappings``,
            ``aggregation_rules``, and ``final_columns`` YAML files.
        artifact_manager: ``ArtifactManager`` instance (unused directly but
            required by ``VocTableCombiner``).

    Returns:
        Combined DataFrame with the final schema as defined by
        ``final_columns.yml``.
    """
    # Load transformation configs
    field_mappings_path = transformation_config.get("field_mappings")
    aggregation_rules_path = transformation_config.get("aggregation_rules")
    final_columns_path = transformation_config.get("final_columns")

    # Create VocTableCombiner
    combiner = VocTableCombiner(
        field_mappings_path=field_mappings_path,
        aggregation_rules_path=aggregation_rules_path,
        final_columns_path=final_columns_path,
    )

    # Convert to DataFrames
    df_screening = pd.DataFrame(screening_results) if screening_results else pd.DataFrame()

    detailed_dfs = {}
    for category, items in detailed_results.items():
        if items:
            detailed_dfs[category] = pd.DataFrame(items)
            log_echo(f"  Category '{category}': {len(items)} items, columns: {list(detailed_dfs[category].columns)}")

    log_echo(f"Combining {len(df_screening)} screening records with {len(detailed_dfs)} detail categories...")

    # Run combination
    combined_df = combiner.combine_tables(
        df_full=df_screening,
        detailed_dfs=detailed_dfs,
    )

    log_echo(f"Combined table: {len(combined_df)} rows × {len(combined_df.columns)} columns")

    return combined_df


async def upload_to_databricks(df: pd.DataFrame, config: dict) -> None:
    """Upload combined results to a Databricks Delta table via MERGE.

    Reads Databricks connection settings from ``config["databricks"]``
    and performs an upsert (merge) on the target table using the
    configured merge keys.

    Args:
        df: Combined DataFrame to upsert.
        config: VOC pipeline config containing a ``databricks`` section
            with ``catalog``, ``schema_name``, ``table_name``,
            ``merge_keys``, and ``enable_upsert`` keys.
    """
    from novus_calls.core.database.databricks import DatabricksConnection, DatabricksTableManager

    db_config = config.get("databricks", {})
    if not db_config or not db_config.get("enable_upsert", False):
        log_echo("Databricks upload disabled in config")
        return

    catalog = db_config.get("catalog", "main")
    schema_name = db_config.get("schema_name", "novus_voc")
    table_name = db_config.get("table_name", "voc_insights")
    merge_keys = db_config.get("merge_keys", ["filename"])

    full_table_name = f"{catalog}.{schema_name}.{table_name}"

    log_echo(f"Uploading {len(df)} rows to {full_table_name}...")

    try:
        db_connection = DatabricksConnection(
            catalog_name=catalog,
            schema_name=schema_name,
        )
        db_manager = DatabricksTableManager(connection=db_connection)

        # Upsert to Delta table
        db_manager.upsert_to_delta_table(
            df=df,
            catalog=catalog,
            schema_name=schema_name,
            table_name=table_name,
            merge_keys=merge_keys,
        )

        log_echo(f"Successfully uploaded to {full_table_name}")
    except Exception as e:
        logger.exception("Databricks upload failed")
        log_echo(f"Databricks upload failed: {e}")
'''
'''
################################################################
# LOAD TINYLLAMA MODEL ONLY ONCE
###############################################################

print("Loading TinyLlama model...")

MODEL_NAME = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

###############################################################
# TOKENIZER
###############################################################

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

###############################################################
# MODEL
###############################################################

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME
)

###############################################################
# DEVICE
###############################################################

device = 0 if torch.cuda.is_available() else -1

###############################################################
# PIPELINE
###############################################################

generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device=device
)

print("MODEL LOADED SUCCESSFULLY")

'''
import streamlit as st

MODEL_PATH = "saved_model"

#########################################################
# LOAD MODEL ONLY ONCE
#########################################################

@st.cache_resource
def load_model():

    print("Loading TinyLlama model...")

    #####################################################
    # TOKENIZER
    #####################################################

    tokenizer = AutoTokenizer.from_pretrained(
    MODEL_PATH,
    local_files_only=True
    )

    #####################################################
    # MODEL
    #####################################################

    model = AutoModelForCausalLM.from_pretrained(
    MODEL_PATH,
    local_files_only=True
    )

    #####################################################
    # DEVICE
    #####################################################

    device = 0 if torch.cuda.is_available() else -1

    #####################################################
    # PIPELINE
    #####################################################

    generator = pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        device=device
    )

    print("MODEL LOADED SUCCESSFULLY")

    return generator

#########################################################
# GLOBAL GENERATOR
#########################################################

generator = load_model()

###############################################################
# PROCESS ALL TRANSCRIPTS
###############################################################

async def process_all_transcripts():

    try:

        #######################################################
        # LOAD YAML CONFIG
        #######################################################

        with open(
            "customer_sentiment_fields.yaml",
            "r",
            encoding="utf-8"
        ) as f:

            fields_config = yaml.safe_load(f)

        #######################################################
        # FIND ALL TRANSCRIPT FILES
        #######################################################

        transcript_files = glob.glob(
            "sample_transcripts/*.json"
        )

        #######################################################
        # STORE RESULTS
        #######################################################

        results = []

        #######################################################
        # PROCESS EACH TRANSCRIPT
        #######################################################

        for file_path in transcript_files:

            try:

                print(f"\nProcessing: {file_path}")

                ###################################################
                # LOAD TRANSCRIPT JSON
                ###################################################

                with open(
                    file_path,
                    "r",
                    encoding="utf-8"
                ) as f:

                    transcript_data = json.load(f)

                ###################################################
                # EXTRACT TRANSCRIPT TEXT
                ###################################################

                full_transcript = _extract_transcript_text(
                transcript_data
                )

                customer_text = extract_customer_only_text(
                full_transcript
                )

                ###################################################
                # VALIDATION
                ###################################################

                if not customer_text.strip():

                    print(
                        f"Skipping empty transcript: {file_path}"
                    )

                    continue

                ###################################################
                # GET METADATA
                ###################################################

                metadata = transcript_data.get(
                    "metadata",
                    {}
                )

                call_id = metadata.get(
                    "call_id",
                    "UNKNOWN"
                )

                ###################################################
                # PROMPT
                ###################################################

                prompt = f"""
You are a sentiment analysis system.

Analyze ONLY the CUSTOMER conversation.

Classify the OVERALL customer sentiment.

Rules:

- Negative:
customer is angry, frustrated, upset,
complaining, dissatisfied, disappointed,
threatening escalation, or unhappy.

- Neutral:
customer is asking questions calmly
without strong emotion.

- Positive:
customer is happy, satisfied,
appreciative, thankful, or pleased.

Return ONLY ONE WORD:

Positive
Neutral
Negative

Customer Conversation:
{customer_text}

Sentiment:
"""
                ###################################################
                # RUN LLM
                ###################################################

                response = generator(
                    prompt,
                    max_new_tokens=5,
                    do_sample=False,
                    temperature=0.0
                )

                print("RAW MODEL OUTPUT:")
                print(response)

                ###################################################
                # CLEAN OUTPUT
                ###################################################

                generated_text = response[0][
                    "generated_text"
                ]

                generated_text = generated_text.replace(
                    prompt,
                    ""
                ).strip()

                generated_text = generated_text.strip()

                ###################################################
                # SENTIMENT EXTRACTION
                ###################################################

                valid_sentiments = [
                    "Positive",
                    "Neutral",
                    "Negative"
                ]

                final_sentiment = "Unknown"

                for sentiment in valid_sentiments:

                    if sentiment.lower() in generated_text.lower():

                        final_sentiment = sentiment
                        break

                ###################################################
                # STORE RESULT
                ###################################################

                results.append({

                    "call_id": call_id,

                    "transcript": full_transcript,

                    "customer_sentiment": final_sentiment
                })

                print(
                    f"{call_id} -> {final_sentiment}"
                )

            #######################################################
            # SINGLE FILE ERROR
            #######################################################

            except Exception as e:

                print(
                    f"Error processing {file_path}: {e}"
                )

        ###########################################################
        # CREATE DATAFRAME
        ###########################################################

        df = pd.DataFrame(results)

        ###########################################################
        # SAVE CSV
        ###########################################################

        df.to_csv(
            "sentiment_results.csv",
            index=False
        )

        ###########################################################
        # FINAL OUTPUT
        ###########################################################

        print("\nCSV FILE CREATED SUCCESSFULLY")

        print(df)

        return df

    ###############################################################
    # MAIN ERROR HANDLING
    ###############################################################

    except Exception as e:

        logger.exception(
            "Sentiment pipeline failed"
        )

        print(f"\nERROR: {str(e)}")

'''
if __name__ == "__main__":
    configure_logging()
    voc_extract()
'''
#
'''
try:

    await process_all_transcripts()

except RuntimeError:

    asyncio.run(
        process_all_transcripts()
    )

from google.colab import files

files.download("sentiment_results.csv")
'''
#
if __name__ == "__main__":

    asyncio.run(
        process_all_transcripts()
    )

'''
sample_json = {
    "transcription": {
        "transcript": "Agent: Hello sir how may I help you today?\n\nCustomer: I am extremely disappointed with the delay in claim settlement.\n\nAgent: I apologize for the inconvenience.\n\nCustomer: This issue has happened multiple times and I am frustrated."
    },
    "metadata": {
        "call_id": "CALL_001",
        "language": "english"
    }
}

import json

with open("sample_transcript.json", "w") as f:
    json.dump(sample_json, f, indent=4)

print("JSON file created successfully")
'''

'''
yaml_content = """
fields:
  - name: customer_sentiment
    description: |
      Analyze ONLY the CUSTOMER statements.

      Determine the overall customer sentiment.

      Allowed values:
      - Positive
      - Neutral
      - Negative
"""

with open("customer_sentiment_fields.yaml", "w") as f:
    f.write(yaml_content)

print("YAML file created successfully")
'''

'''
import os
import json

os.makedirs("transcripts", exist_ok=True)

sample_calls = [

{
    "filename": "call_001.json",
    "data": {
        "transcription": {
            "transcript": """RM: Good morning sir, how may I help you today?

Customer: I wanted to check why my credit card reward points are not updated yet.

RM: Let me quickly check that for you.

Customer: Honestly this has happened multiple times and it becomes frustrating.

RM: I understand your concern sir.

Customer: But I appreciate that you are checking it properly now."""
        },
        "metadata": {
            "call_id": "CALL_001",
            "language": "english"
        }
    }
},

{
    "filename": "call_002.json",
    "data": {
        "transcription": {
            "transcript": """RM: Hello ma'am, how can I assist you?

Customer: My insurance claim is still pending after three weeks.

RM: I apologize for the delay.

Customer: I am extremely unhappy with the service quality.

RM: I will escalate this immediately.

Customer: Please do because this is becoming unacceptable."""
        },
        "metadata": {
            "call_id": "CALL_002",
            "language": "english"
        }
    }
},

{
    "filename": "call_003.json",
    "data": {
        "transcription": {
            "transcript": """RM: Welcome sir.

Customer: I was initially upset about the EMI charges.

RM: I understand sir.

Customer: But after your explanation it makes more sense now.

RM: Glad I could help.

Customer: Thank you, I am satisfied now."""
        },
        "metadata": {
            "call_id": "CALL_003",
            "language": "english"
        }
    }
},

{
    "filename": "call_004.json",
    "data": {
        "transcription": {
            "transcript": """RM: Good evening ma'am.

Customer: The mobile app keeps crashing during transactions.

RM: Sorry for the inconvenience.

Customer: Sometimes it works fine but today it failed again during payment.

RM: Our technical team is already working on this.

Customer: I hope this gets fixed soon."""
        },
        "metadata": {
            "call_id": "CALL_004",
            "language": "english"
        }
    }
},

{
    "filename": "call_005.json",
    "data": {
        "transcription": {
            "transcript": """RM: Hello sir.

Customer: I wanted to thank your branch team.

RM: That's great to hear.

Customer: Last month I was upset about the loan delay.

RM: Yes sir.

Customer: But your staff handled everything professionally afterwards."""
        },
        "metadata": {
            "call_id": "CALL_005",
            "language": "english"
        }
    }
},

{
    "filename": "call_006.json",
    "data": {
        "transcription": {
            "transcript": """RM: Good afternoon.

Customer: My account got debited twice yesterday.

RM: Let me check the transaction details.

Customer: I am worried because this amount is important for me.

RM: The duplicate debit should reverse automatically.

Customer: Okay, I feel slightly relieved now."""
        },
        "metadata": {
            "call_id": "CALL_006",
            "language": "english"
        }
    }
},

{
    "filename": "call_007.json",
    "data": {
        "transcription": {
            "transcript": """RM: Hello sir.

Customer: Your executive promised a callback but nobody contacted me.

RM: I sincerely apologize.

Customer: This is really poor customer service.

RM: I will personally follow up.

Customer: Fine, I will wait till tomorrow."""
        },
        "metadata": {
            "call_id": "CALL_007",
            "language": "english"
        }
    }
},

{
    "filename": "call_008.json",
    "data": {
        "transcription": {
            "transcript": """RM: Welcome ma'am.

Customer: The account opening process was smooth.

RM: Glad to hear that.

Customer: Although document verification took slightly longer than expected.

RM: Thank you for your patience.

Customer: Overall the experience was good."""
        },
        "metadata": {
            "call_id": "CALL_008",
            "language": "english"
        }
    }
},

{
    "filename": "call_009.json",
    "data": {
        "transcription": {
            "transcript": """RM: Good morning sir.

Customer: I am confused about these hidden charges.

RM: Let me explain the fee structure.

Customer: I still think the charges are unfair.

RM: I understand your concern.

Customer: Honestly I am disappointed."""
        },
        "metadata": {
            "call_id": "CALL_009",
            "language": "english"
        }
    }
},

{
    "filename": "call_010.json",
    "data": {
        "transcription": {
            "transcript": """RM: Hello ma'am.

Customer: I received excellent support from your branch.

RM: Thank you for the feedback.

Customer: Earlier I faced some delays but your team resolved everything quickly.

RM: Happy to assist.

Customer: I am very satisfied with the service now."""
        },
        "metadata": {
            "call_id": "CALL_010",
            "language": "english"
        }
    }
}

]

for item in sample_calls:

    with open(
        f'transcripts/{item["filename"]}',
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            item["data"],
            f,
            indent=4
        )

print("10 transcript JSON files created successfully")
'''